apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: myk8smeantest
  name: myk8smeantest
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: myk8smeantest
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: myk8smeantest
    spec:
      containers:
        - image: 561931347622.dkr.ecr.us-east-2.amazonaws.com/myk8smeantest:0.1.2
          name: myk8smeantest
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
